version: '3.5'

services:
  app:
    image: 'weather:latest'
    build:
      context: .
    ports:
      - "9595-9597:8080"
    environment:
      - WEATHER_STACK_API_KEY=${WEATHER_STACK_API_KEY}
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge