
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weatherdb

  h2:
    console:
      enabled: true

  config:
    import : optional:file:.env[.properties]
    # Add working directory to the classpath or use absolute path


weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${WEATHER_STACK_API_KEY}
